### ISSUE TITLE
Add a new service Data BNF

### ISSUE THREAD

**Issue by lrichelle** [jweisman/alma-refine#10]
Dear Mr Weisman,
This feature is really fine !
Could it be possible to add URI's from french Data.bnf  (https://data.bnf.fr/en/ )?

I think here is documentation : 
https://data.bnf.fr/en/semanticweb
and 
http://api.bnf.fr/sparql-endpoint-de-databnffr

Data.bnf has links with Wikidata and I think BNF has dumps of external links in this file ftp://databnf:databnf@pef.bnf.fr/DATA/databnf_externalrefs_xml.tar.gz (from page http://api.bnf.fr/dumps-de-databnffr)

Our aim is to enrich our records with data.bnf links for marc21 1xx, 6xx, 7xx fields (subfield 1), mostly for rare books materials as a first step. 
Do you think you could add this service to Alma refine app?
Thanks for your help !
Best regards,
Laurence

Laurence Richelle
Liège Université Library
Belgium
laurence.richelle@uliege.be

**Comment by jweisman** [comment]
Thanks for the feedback. We’ll look into this suggestion.

**Comment by jweisman** [comment]
Hi there. We were able to find a reconciliation service which supports BNF (via VIAF): http://refine.codefork.com

We implemented it in BETA mode- would be great if you could try it out and let us know how it works. Also, if you have some sample MARC records with terms authorized by BNF that would be helpful to test with.

Thanks.

**Comment by lrichelle** [comment]
Hi, I've made some tests in our sandbox and production environments. 
Joined are some results of these tests and a sample of marc records. Hope this will help! Tell me if comments are pertinent for you. Perhaps some fields (subject headings in 650 for exemple) could be excluded from the job since the service works from Viaf?  Many thanks ! 
laurence

[Alma-Refine-BNF-32ULG.docx](https://github.com/jweisman/alma-refine/files/5537246/Alma-Refine-BNF-32ULG.docx)

[32ULG-Marc-Refine-BNF.txt](https://github.com/jweisman/alma-refine/files/5537237/32ULG-Marc-Refine-BNF.txt)

**Comment by jweisman** [comment]
Thanks very much for your useful comments and the sample records. I have reviewed the comments and tried to answer below. One note- you can adjust the refinement fields and other settings as specified below. I updated the defaults as best as I could based on how I understood your comments:

![Screen Shot 2020-11-16 at 13 32 53](https://user-images.githubusercontent.com/80420/99248425-1661df00-2811-11eb-94d3-f98021021ef2.png)

We released a new version which you're welcome to check out. If you have additional comments or clarifications we'd be happy to review. 

### General
* Using AlmaRefine makes the language interface change : I use to work with English interface > I applied Alma Refinement on a record and then noticed that language interface had changed to French.
Not sure 
_I can't reproduce this- perhaps a screen cast would help here?_
* The app creates a $$0 subfield. Shouldn’t it be a $$1 whith this Data.BnF ? 
_This can be changed in the [preferences](https://github.com/jweisman/alma-refine/wiki/Help#refine-services-1)- I updated the default to set $1_
* Probably the fact that it use Viaf makes some incongruences in some refinements suggested (see below for exemple on 751 or 650 fields)

### Examples
* MMS ID 9920361990502321
** 700 > ok. In this case, there’s only one choice. But it would be easier to see also subfield $$d and not just $$a from Alma Marc Record. 
_ I'll add an enhancement request to see additional fields in the display (#11)_
** For 751 field
_The index can be changed in the [preferences](https://github.com/jweisman/alma-refine/wiki/Help#refine-services-1)- I updated the default to use the Geographic location index_
** 752 field : seems it check personnal name headings ? 
_The index can be changed in the [preferences](https://github.com/jweisman/alma-refine/wiki/Help#refine-services-1)- I updated the default to use the Geographic location index_
* MMS ID 990001861680502321
** 100 field : in this case, it’s quite impossible to choose the refinement without checking $$d
_ I'll add an enhancement request to see additional fields in the display (#11)_
* MMS ID 990009208530502321
** 130 field : I think refinements proposed are not adequate. But I have to check the heading here
* MMS ID 9919411075302321
*	MMS ID 990000556630502321
** 710 field  $a Couvent des Récollets - The same problem as for 100 or 700 $d : the lack of subfield $b in the display (column Refine Fields) prevent to select a refinement in the list.
_ I'll add an enhancement request to see additional fields in the display (#11)_
* MMS ID 990001528610502321
** 600 field $a Lambert : not adequate proposals
_Not sure there's much I can do here- this is what the service is returning_
* MMS ID 990000342320502321
** 650 Field « Cosmographie » is a RAMEAU subject heading 
_It's not clear how this should be changed?_
* MMS ID 990001782190502321
_I'm not sure I understand the issue well enough here_

**Comment by lrichelle** [comment]
Hi,
Ok, I'll look at the preferences, thanks!

For the problem of language change, see the screencasts here : 
[CloudApp-Change-Interface-Language-32ULG.zip](https://github.com/jweisman/alma-refine/files/5558993/CloudApp-Change-Interface-Language-32ULG.zip)
(Using E-Collections quick update app is the same)

MMS ID 990001782190502321
I'm not sure I understand the issue well enough here
=> there are two issues
The 1st one is that using the refinement change the heading wrongly. I thought this happened only for 700 fields but I saw the same for 100 field : look here  
![100-add-dates-in-subfield-a](https://user-images.githubusercontent.com/73102583/99511714-e9d0d300-2988-11eb-943d-941caf7e7746.png)

and for 700 the same 
![700-add-dates-in-subfield-a](https://user-images.githubusercontent.com/73102583/99512578-ebe76180-2989-11eb-9d1a-a5979feab06a.png)

The original record had $$a $$d $$e subfields 

I check again the 2nd issue and try to explain better what I get;
I continue to test.
Have a nice day
Laurence

**Comment by jweisman** [comment]
Thanks for your comments! It helps me to understand. 

It seems that the BNF refine service is returning the name with the additional fields. See the results in this [raw response](https://conciliator.herokuapp.com/reconcile/viafproxy/BNF?queries=%7B%22ede3f37e%22:%7B%22query%22:%22Johannes%20de%20Sacro%20Bosco,%2011..-1256?%22,%22limit%22:10%7D,%22de775b13%22:%7B%22query%22:%22Italie%22,%22limit%22:10,%22type%22:%22/location/location%22%7D,%221ef62127%22:%7B%22query%22:%22Capuano,%20Francesco%22,%22limit%22:10%7D%7D).

To avoid this, you can turn off term correction for the BNF service and just update the $1 with the URI. This capability is [documented here](https://github.com/jweisman/alma-refine/wiki/Help#refine-services-1) and shown in the screenshot:

![Screen Shot 2020-11-18 at 15 38 55 ](https://user-images.githubusercontent.com/80420/99537783-c58aeb80-29b4-11eb-81ec-d8a059e607a9.png)

Regarding the change of language- I've opened #13 for this.

**Comment by lrichelle** [comment]
Great ! I'll adjust the configuration for our needs thus.
Many thanks!

**Comment by jweisman** [comment]
FYI- #12 was implemented. Please check out the comments there and the [release notes](https://github.com/jweisman/alma-refine/releases/tag/v0.2.0#user-content-collapsed) for more information. Let us know how that works for you.

**Comment by lrichelle** [comment]
Hi, Yes, that's fine. Just a pity that one can't see both the complete heading and the refinement at the same time. 

I've now another problem with Chrome browser  - I suppose since the new version of the app as I worked with Chrome for the first tests : once I've clicked on the "Begin refining" button, nothing more happens (see screenshot).

For some headings, the refinement service seems to retrieve bad ids. For exemple, MMS ID 990007826750502321, the heading Homère in 100 field > the refinement is not correct as it gives this : https://data.bnf.fr/FRBNF119076881
How can we correct this?

Thanks!
Laurence
![AlmaRefine-ChromeBrowser](https://user-images.githubusercontent.com/73102583/100587797-533dd380-32f1-11eb-9c57-a8171ac42b8e.jpg)

**Comment by jweisman** [comment]
Hi Laurence. Thanks for your comments. Regarding the never-ending spinner- is that still happening? I'l able to refine this record without a problem.

Regarding the incorrect IDs, it appears that BNF via VIAF service is sometimes returning these strange IDs. Not sure what the root-cause is, but the pattern seems to be - if it's preceded by FRBNF, then remove it and the last character. See the examples below. If this seems right to you, we can add a change to handle that conversion.

```
setUris 15238307 https://data.bnf.fr/15238307
setUris 15324401 https://data.bnf.fr/15324401
setUris 11865386 https://data.bnf.fr/11865386
setUris FRBNF11934078X https://data.bnf.fr/11934078
setUris FRBNF118652783 https://data.bnf.fr/11865278
```

**Comment by lrichelle** [comment]
Hi,
The never-ending sprinner problem with Chrome still happens on my browser.

For incorrect IDs, yes, it should be ok removing FRBNF and last character, thanks !

**Comment by jweisman** [comment]
Hi - we released the version which handles the ID conversion. Please let us know how that looks.

Regarding the spinning, if it continues please open a new issue with details about the record you're trying to refine.

Thanks!
