### ISSUE TITLE
Base URL for GND reconcile is obsolete

### ISSUE THREAD

**Issue by graemart** [jweisman/alma-refine#11]
Hi
The base URL for the GND reconcile service (https://test.lobid.org) registered in Alma Refine seems to be obsolete. According to https://blog.lobid.org/2018/08/27/openrefine.html it is now https://lobid.org/.
I get no results with the base URL configured as it s now.

Could you please check?

Best regards,
Martin Gränicher

**Comment by jweisman** [comment]
Hi- this was fixed and a new version was released.
