### ISSUE TITLE
Language changes when using Cloud App

### ISSUE THREAD

**Issue by jweisman** [jweisman/alma-refine#13]
Reported by @lrichelle in #11.

See this screencast:
[CloudApp-Change-Interface-Language-32ULG.zip](https://github.com/jweisman/alma-refine/files/5558993/CloudApp-Change-Interface-Language-32ULG.zip)

**Comment by ori229** [comment]
@lrichelle, this was a bug on Alma's side - will be solved with Alma's Feb Release.
