### ISSUE TITLE
Alma Refine - Cannot scroll through term descriptions

### ISSUE THREAD

**Issue by selamarin** [jweisman/alma-refine#3]
If the description of the heading (which is displayed as a pop up you trigger by hovering over the 'i' icon) requires you to scroll, you can't get to the pop up to scroll – as soon as your mouse leaves the 'i' icon, the pop up disappears. Clicking on the 'i' icon selects the heading and closes the list. If I use keyboard commands to force it to focus on the ‘I’ icon, I can then use the mouse to scroll, but most users won’t know how to do this (unless they’re used to adaptive technologies for disabilities) This is particularly unhelpful when picking between common name headings. For an example, if you try to refine the term 'galleries' and scroll through descriptions of 'dwarf galleries' or 'long galleries', you cannot get to the popup to scroll.

**Comment by jweisman** [comment]
@selamarin - I think I found a better implementation that supports scrolling. Can you test again? 

Fixed by 7d93ed79a7448c0b034c76f29964598408393287
