### ISSUE TITLE
Add additional service - GND 

### ISSUE THREAD

**Issue by CamilleGh** [jweisman/alma-refine#8]
Dear Mr. Weisman,
we would like to know if it's possible to use the Alma refine App with "GND/Lobid" as a service to refine bibliographic records.
Service-URL for OpenRefine: https://lobid.org/gnd/reconcile
See also:
https://blog.lobid.org/2018/08/27/openrefine.html
https://lobid.org/resources/api

Can you tell us if it's possible and if yes, how should we process ?
Thank you for your help
Camille Ghelfi
Swiss National Library

**Comment by jweisman** [comment]
Hi @CamilleGh . It seems like it should be possible for us to add the GND/Lobid service. Could you provide a couple of sample MARC records with values from the GND so we can test the service? Also, which fields would the service be relevant for?

**Comment by CamilleGh** [comment]
Dear Mister Weisman,
Here are 4 MARC records. 
The records with the MMS ID 991018073834403976 and MMS ID 991018025110303976 should be refined using the field 100 subfield d and add the GND-Number with prefix (DE-588) in the subfield $$0.
The records MMS ID 991018031063803976 and MMS ID 991018033226603976 should not find any match.
I hope we understood correctly what you asked for.
Thank you
Camille
[alma-refine.zip](https://github.com/jweisman/alma-refine/files/5060861/alma-refine.zip)

**Comment by jweisman** [comment]
This is perfect- thanks. I have added the service and confirmed that it works with the records you provided. A few notes:
* It looks like 100$$a should be the match field
* According to the [GND documentation](https://d-nb.info/standards/elementset/gnd), the URI should be in this format: `https://d-nb.info/gnd/<ID>`, i.e. https://d-nb.info/gnd/118514091
* An example of the added $$0 is shown in the image below. 

<img width="1315" alt="gnd-refine" src="https://user-images.githubusercontent.com/80420/90024418-823a2600-dcbd-11ea-8c9d-a773d2b7ee38.png">

Please let me know if you have any comments. Otherwise I can release this so you can play with it in your environment.

**Comment by CamilleGh** [comment]
Dear Mr Weisman,
it's look great, you can release it.
Thank you
Camille

**Comment by jweisman** [comment]
Thanks for the feedback. The GND service is now available in the Alma Refine app. You can work with it in your environment and let me know if you have any issues.

**Comment by CamilleGh** [comment]
Dear Mr. Weisman,
We found a problem with the indexes : w
[AlmaRefine_Indexes (1).docx](https://github.com/jweisman/alma-refine/files/5166403/AlmaRefine_Indexes.1.docx)
hen we choose an index, for exemple "schlagwort" for the 650 fields, nothing happens the "Retrieving refinements...." stays for ever. It's not the case when we didn't choose an index
You can see the details in the attached file.
Kind regards
Camille

**Comment by jweisman** [comment]
Thanks for your report. We have made a fix for the GND service implementation. Please note that the service only supports selecting 0 or 1 indexes. Let us know how it goes.

**Comment by CamilleGh** [comment]
Thank you for the fix, it seems to work now.

**Comment by CamilleGh** [comment]
But we have another problem with the preview from lobid.org. The content is now blocked. Before we could see the informations and open the link, and now the content is blocked.
Can you check what happened ?
Thank you
Camille
![lobid](https://user-images.githubusercontent.com/38520365/92587805-6748da80-f298-11ea-91fd-ede654909ae6.png)
![image-2020-09-08-16-32-22-315](https://user-images.githubusercontent.com/38520365/92587827-729c0600-f298-11ea-9e9e-078eccbbd03d.png)

**Comment by jweisman** [comment]
Hi again. Looks like the GND service URL changed from lobid.org to test.lobid.org (see [here](https://lobid.org/gnd/reconcile)). We made a small release to update.

**Comment by CamilleGh** [comment]
Great, thank you very much
Camille
