### ISSUE TITLE
what stored from Wikidata in $1 is not URI and $a is changed too

### ISSUE THREAD

**Issue by huilinglee886** [jweisman/alma-refine#9]
Dear Mr. Weisman,

Thank you for develop this cloud app for Alma, it's very very helpful!
I tried a record with Alma Refine using Wikidata, and found that what stored in $1 is entity ID, not URI; also the content in $a is replaced by the label from Wikidata, which broke the existing linking between authority file (no matter CZ or local) and bib record. I understand data reconciliation may suggest transferring the original text, but in MARC bib record it seems not quite appropriate. Please consider just store the URI from Wikidata, but not changing the $a content, thank you.
Here are some screenshots of refined bib, taking "Harry Potter and the sorcerer's stone by J.K. Rowling" as example:

before refinning:
![image](https://user-images.githubusercontent.com/70013182/90993955-92210680-e5e9-11ea-8670-0efe4ae4466a.png)
![image](https://user-images.githubusercontent.com/70013182/90993785-c8aa5180-e5e8-11ea-9ed0-046a4ade136e.png)

after:
![image](https://user-images.githubusercontent.com/70013182/90993790-ccd66f00-e5e8-11ea-96e3-103f6f86a21a.png)
![image](https://user-images.githubusercontent.com/70013182/90993808-e24b9900-e5e8-11ea-9976-09be842feeec.png)

Best Regards,
Helen Lee

**Comment by jweisman** [comment]
Hi @huilinglee886 . Thanks for your comment. We have released a new version with a few changes:
1. Updated the settings of the Wikidata service to include the URI as defined [here](https://meta.wikimedia.org/wiki/Wikidata/Notes/URI_scheme).
2. Added a setting to control whether the value in the bibliographic record is changed to match the refinement term. See the [updated help](https://github.com/jweisman/alma-refine/wiki/Help#refine-services-1).

Let us know how if you run into any issues.

**Comment by huilinglee886** [comment]
Hi @jweisman ,
Thank you for the update, I've tested few records and it worked fine! For the URI part, I didn't see the "URI subfield" in settings actually, but after adding Prefix, it could also apply to entity stored in $1. Maybe this is where I missed when first testing, I apologize if it caused you extra work. Thanks again for what you've done, it's really appreciated.

Best Regards,
Helen Lee

**Comment by jweisman** [comment]
Thanks for the feedback!
